conocimiento = {
    'usuarios': {
        'usuario1': {'gusto': ['Aventura', 'Ciencia ficción'], 'edad': 25},
        'usuario2': {'gusto': ['Romance', 'Drama'], 'edad': 30},
        'usuario3': {'gusto': ['Aventura', 'Comedia'], 'edad': 20},
        'Yona': {'gusto': ['Romance', 'Animación', 'Ciencia ficción'], 'edad': 21},
        'Nata': {'gusto': ['Romance', 'Drama', 'Acción'], 'edad': 21},
        'Otto': {'gusto': ['Drama', 'Fantasía'], 'edad': 25},
        'Roberto': {'gusto': ['Romance'], 'edad': 22},
        'Farit': {'gusto': ['Aventura'], 'edad': 22},
    },
    'peliculas': {
        'Star Wars': {'genero': 'Ciencia ficción', 'edad_recomendada': 13},
        'La La Land': {'genero': 'Romance', 'edad_recomendada': 13},
        'Toy Story': {'genero': 'Aventura', 'edad_recomendada': 0},
        'Inception': {'genero': 'Ciencia ficción', 'edad_recomendada': 13},
        'Titanic': {'genero': 'Romance', 'edad_recomendada': 13},
        'The Dark Knight': {'genero': 'Acción', 'edad_recomendada': 13},
        'The Godfather': {'genero': 'Drama', 'edad_recomendada': 17},
        'The Shawshank Redemption': {'genero': 'Drama', 'edad_recomendada': 17},
        'The Matrix': {'genero': 'Ciencia ficción', 'edad_recomendada': 13},
        'Jurassic Park': {'genero': 'Aventura', 'edad_recomendada': 13},
        'Finding Nemo': {'genero': 'Animación', 'edad_recomendada': 0},
        'The Lion King': {'genero': 'Animación', 'edad_recomendada': 0},
        'Avatar': {'genero': 'Ciencia ficción', 'edad_recomendada': 13},
        'Frozen': {'genero': 'Animación', 'edad_recomendada': 0},
        'Spider-Man: Into the Spider-Verse': {'genero': 'Animación', 'edad_recomendada': 0},
        'Pulp Fiction': {'genero': 'Drama', 'edad_recomendada': 17},
        'The Avengers': {'genero': 'Acción', 'edad_recomendada': 13},
        'Back to the Future': {'genero': 'Ciencia ficción', 'edad_recomendada': 0},
        'The Lord of the Rings: The Fellowship of the Ring': {'genero': 'Fantasía', 'edad_recomendada': 13},
        'Forrest Gump': {'genero': 'Drama', 'edad_recomendada': 13},
        'Gladiator': {'genero': 'Acción', 'edad_recomendada': 17},
        'Braveheart': {'genero': 'Acción', 'edad_recomendada': 17},
        'The Notebook': {'genero': 'Romance', 'edad_recomendada': 13},
        'Moana': {'genero': 'Animación', 'edad_recomendada': 0},
        'Shrek': {'genero': 'Animación', 'edad_recomendada': 0},
        'Pirates of the Caribbean: The Curse of the Black Pearl': {'genero': 'Aventura', 'edad_recomendada': 13},
        'Mad Max: Fury Road': {'genero': 'Acción', 'edad_recomendada': 17},
        'Interstellar': {'genero': 'Ciencia ficción', 'edad_recomendada': 13},
        'Guardians of the Galaxy': {'genero': 'Ciencia ficción', 'edad_recomendada': 13},
    }
}
